services:
    app:
        build: .
        container_name: laravel_app
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
        depends_on:
            - db
            - minio

    nginx:
        image: nginx:latest
        container_name: laravel_nginx
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/html
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app

    db:
        image: postgres:latest
        container_name: laravel_db
        environment:
            POSTGRES_DB: laravel
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: secret
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data

    minio:
        image: minio/minio
        container_name: laravel_minio
        environment:
            MINIO_ROOT_USER: minioadmin
            MINIO_ROOT_PASSWORD: minioadmin
        command: server /data --console-address ":9001"
        ports:
            - "9000:9000"
            - "9001:9001"
        volumes:
            - minio_data:/data

    createbuckets:
        image: minio/mc
        depends_on:
            - minio
        entrypoint: >
            /bin/sh -c "
            sleep 5;
            mc alias set myminio http://minio:9000 minioadmin minioadmin;
            mc mb myminio/my-bucket;
            mc anonymous set public myminio/my-bucket;
            exit 0;
            "

    pgadmin:
        image: dpage/pgadmin4
        container_name: laravel_pgadmin
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: admin
        ports:
            - "5050:80"
        volumes:
        - pgadmin_data:/var/lib/pgadmin
        - ./pgadmin/servers.json:/pgadmin4/servers.json

        depends_on:
            - db

volumes:
    pgdata:
    minio_data:
    pgadmin_data:
